name: pytorch
channels:
 - defaults
 # - soumith
#  - conda-forge
dependencies:
- python=3.6
- flake8
- cython
- pandas
- numba
- lxml
- beautifulsoup4
- requests
- html5lib
- gensim  # =0.12.4
- seaborn
- joblib
- scikit-learn
#- pymc3
- jupyter
# - pytorch
# - torchvision
- bcolz
- pip:
  # - keras
  # - chainer
  # - requests_cache
  # - pandas_datareader
  # - tsfresh
  # - pyflux
  # - pystan
  # - parsec
  # - grequests
  # - "ipython[notebook]<4"
  - toolz
  # - snakeviz
  # - pygraphviz
  # - fuzzywuzzy
  # - autograd
  # - voluptuous
  # - pytest
  - feather-format  # export MACOSX_DEPLOYMENT_TARGET=10.10
  # - aiohttp
  # - requests-cache
  # - pymining
  # - pymc3
  # - '--process-dependency-links git+https://github.com/pymc-devs/pymc3'
  # - 'git+https://github.com/pymc-devs/pymc3'
